version: '3.1'

services:
  db:
    build: docker/mySQL
    container_name: mysql
    image: nobsxd/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306



  phpmyadmin:
    build: docker/phpadmin
    image: nobsxd/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

  api_service:
    depends_on:
      - phpmyadmin
      - db
    build: .
    image: nobsxd/dota:spring
    container_name: spring

    ports:
      - 8082:8082

