name: "Ruby on Rails CI"
on:
  push:
    branches: 
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build compose    
      run: docker-compose build
      
    
    
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
           host: ${{secrets.SSH_PRIVATE_HOST_DOTA2}}
           user: ${{secrets.SSH_PRIVATE_USER_DOTA2}}
           private_key: ${{secrets.SSH_PRIVATE_KEY_DOTA2}}
           
           command: |
             echo '--- START WORK ON REMOTE SERVER ---';
             docker images
             
            
  
      
