name: "Ruby on Rails CI"
on:
  push:
    branches: 
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
           host: ${{secrets.SSH_PRIVATE_HOST_DOTA2}}
           user: ${{secrets.SSH_PRIVATE_USER_DOTA2}}
           private_key: ${{secrets.SSH_PRIVATE_KEY_DOTA2}}
           command: |
            
  
      
