name: "Ruby on Rails CI"
on:
  push:
    branches: 
      - master
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_PRIVATE_HOST_DOTA2}}
          user: ${{secrets.SSH_PRIVATE_USER_DATA2}}
          private_key: ${{secrets.SSH_PRIVATE_KEY_DOTA2}}
          command: |
            
            docker-compose down;
            docker rmi nobsxd/dota
            docker-compose up -d --build;
         
