name: "Ruby on Rails CI"
on:
  push:
    branches: 
      - master
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          bundler-cache: true
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: "${{SSH_PRIVATE_HOST_DOTA}}"
          user: ${{SSH_PRIVATE_USER_DOTA2}}
          private_key: ${{SSH_PRIVATE_KEY_DOTA2}}
          command: |
            
            docker-compose down;
            docker rmi nobsxd/dota
            docker-compose up -d --build;
         
