name: "Ruby on Rails CI"
on:
  push:
    branches: 
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: mvn clean
      run: mvn clean
    - name: instal
      run: mvn install


    
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build compose    
      run: docker-compose build
      
    
    
    
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
           host: ${{secrets.SSH_PRIVATE_HOST_DOTA2}}
           user: ${{secrets.SSH_PRIVATE_USER_DOTA2}}
           private_key: ${{secrets.SSH_PRIVATE_KEY_DOTA2}}
           
           command: |
             echo '--- START WORK ON REMOTE SERVER ---';
             docker images
             
            
  
      
