name: "Ruby on Rails CI"
on:
  push:
    branches: 
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_TOKEN}}
    - name: test docker
      run: docker-compose up -d --build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
           host: ${{secrets.SSH_PRIVATE_HOST_DOTA2}}
           user: ${{secrets.SSH_PRIVATE_USER_DOTA2}}
           private_key: ${{secrets.SSH_PRIVATE_KEY_DOTA2}}
           
           command: |
             echo '--- START WORK ON REMOTE SERVER ---';
             docker images
             
            
  
      
